# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsinfo',
            options={'verbose_name': 'News Information', 'verbose_name_plural': 'News Informations'},
        ),
    ]
