# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneWaySeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name')),
                ('mobile_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('passport_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Number')),
                ('passport_exp', models.DateField(blank=True, null=True, verbose_name='Passport Expiry')),
                ('booking_agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Booking Agent')),
                ('rate_given', models.IntegerField(blank=True, default=0, null=True, verbose_name='Given Rate')),
            ],
            options={
                'verbose_name': 'One Way Seat',
                'verbose_name_plural': 'One Way Seats',
                'db_table': 'one_way_seat',
            },
        ),
        migrations.CreateModel(
            name='OneWaySeatRemarkInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_remark', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('supplier_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneway_seat_detail', to='flight_fixed_departure.OneWaySeat')),
            ],
            options={
                'verbose_name': 'One Way Seat Remark',
                'verbose_name_plural': 'One Way Seat Remarks',
                'db_table': 'oneway_seat_remark',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=150, unique=True, verbose_name='Sector')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='SupplierDepartureSeatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('mobile_no', models.IntegerField(blank=True, default=0, null=True, verbose_name='Mobile Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('passport_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Number')),
                ('passport_exp', models.DateField(blank=True, null=True, verbose_name='Passport Expiry')),
                ('booking_agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Booking Agent')),
                ('rate_given', models.IntegerField(default=0, verbose_name='Given Rate')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_seat_sector', to='flight_fixed_departure.Sector')),
            ],
            options={
                'verbose_name': 'Round Trip Departure Seat',
                'verbose_name_plural': 'Round Trip Departure Seats',
                'db_table': 'supplier_departure_seat_info',
            },
        ),
        migrations.CreateModel(
            name='SupplierDepartureSeatRemarkInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_remark', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('supplier_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_supplier_departure_detail', to='flight_fixed_departure.SupplierDepartureSeatInfo')),
            ],
            options={
                'verbose_name': 'Seat Departure Remark',
                'verbose_name_plural': 'Seat Departure Remarks',
                'db_table': 'seat_departure_remark',
            },
        ),
        migrations.CreateModel(
            name='SupplierDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150, verbose_name='Supplier Name')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('departure_flt_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dep. Flight No.')),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='Return Time')),
                ('return_flt_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ret. Flight No.')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Departure Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('departure_seat_availability', models.IntegerField(blank=True, null=True, verbose_name='Departure Seat Availability')),
                ('return_seat_availability', models.IntegerField(blank=True, null=True, verbose_name='Return Seat Availability')),
                ('total_departure_seats', models.IntegerField(blank=True, null=True, verbose_name='Total Dep. Seats')),
                ('total_return_seats', models.IntegerField(blank=True, null=True, verbose_name='Total Ret. Seats')),
                ('dep_rate_flash', models.IntegerField(blank=True, null=True, verbose_name='Dep. Rate Flash')),
                ('ret_rate_flash', models.IntegerField(blank=True, null=True, verbose_name='Ret. Rate Flash')),
                ('other_details', models.TextField(blank=True, null=True, verbose_name='Other Details')),
                ('dep_rate_supplier', models.IntegerField(blank=True, null=True)),
                ('ret_rate_supplier', models.IntegerField(blank=True, null=True)),
                ('oneway_time', models.TimeField(blank=True, null=True, verbose_name='One Way Time')),
                ('oneway_date', models.DateField(blank=True, null=True, verbose_name='One Way Date')),
                ('oneway_rate_supplier', models.IntegerField(blank=True, null=True, verbose_name='One Way Rate Supplier')),
                ('oneway_seat_availability', models.IntegerField(blank=True, null=True, verbose_name='One Way Seat Availability')),
                ('oneway_rate_flash', models.IntegerField(blank=True, null=True, verbose_name='One Way Rate Flash')),
                ('oneway_flt_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='One Way Flight No.')),
                ('total_one_way_seats', models.IntegerField(blank=True, null=True, verbose_name='Total One Way Seats')),
                ('sectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sector', to='flight_fixed_departure.Sector')),
            ],
            options={
                'verbose_name': 'Supplier Detail',
                'verbose_name_plural': 'Supplier Details',
                'db_table': 'supplier_details',
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_remark', models.TextField(blank=True, null=True, verbose_name='Payment Remarks')),
                ('supplier_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_remarks', to='flight_fixed_departure.SupplierDetails')),
            ],
            options={
                'verbose_name': 'Supplier Payment Remark',
                'verbose_name_plural': 'Supplier Payment Remarks',
                'db_table': 'supplier_payment_remark',
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnSeatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('mobile_no', models.IntegerField(blank=True, default=0, null=True, verbose_name='Mobile Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('passport_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Number')),
                ('passport_exp', models.DateField(blank=True, null=True, verbose_name='Passport Expiry')),
                ('booking_agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Booking Agent')),
                ('rate_given', models.IntegerField(default=0, verbose_name='Given Rate')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_seat_sector', to='flight_fixed_departure.Sector')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_details', to='flight_fixed_departure.SupplierDetails')),
            ],
            options={
                'verbose_name': 'Round Trip Return Seat',
                'verbose_name_plural': 'Round Trip Return Seats',
                'db_table': 'supplier_return_seat_info',
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnSeatRemarkInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_remark', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('supplier_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_supplier_return_detail', to='flight_fixed_departure.SupplierReturnSeatInfo')),
            ],
            options={
                'verbose_name': 'Seat Return Remark',
                'verbose_name_plural': 'Seat Return Remarks',
                'db_table': 'seat_return_remark',
            },
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='triptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flight_fixed_departure.TripType', verbose_name='Type of Trip'),
        ),
        migrations.AddField(
            model_name='supplierdepartureseatinfo',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_detail', to='flight_fixed_departure.SupplierDetails'),
        ),
        migrations.AddField(
            model_name='sector',
            name='triptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flight_fixed_departure.TripType', verbose_name='Type of Trip'),
        ),
        migrations.AddField(
            model_name='onewayseat',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneway_seat_sector', to='flight_fixed_departure.Sector'),
        ),
        migrations.AddField(
            model_name='onewayseat',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneway_supplierdetails', to='flight_fixed_departure.SupplierDetails'),
        ),
    ]
