# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdetails',
            name='departure_seat_availability',
            field=models.IntegerField(default=0, verbose_name='Departure Seat Availability'),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='return_seat_availability',
            field=models.IntegerField(default=0, verbose_name='Return Seat Availability'),
        ),
    ]
