# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWaySeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('mobile_no', models.CharField(max_length=30, verbose_name='Mobile Number')),
                ('date_of_birth', models.IntegerField(blank=True, default=0, null=True, verbose_name='Date of Birth')),
                ('passport_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Number')),
                ('passport_exp', models.DateField(blank=True, null=True, verbose_name='Passport Expiry')),
                ('booking_agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Booking Agent')),
                ('rate_given', models.IntegerField(default=0, verbose_name='Given Rate')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneway_supplierdetails', to='flight_fixed_departure.SupplierDetails')),
            ],
            options={
                'verbose_name': 'One Way Seat',
                'verbose_name_plural': 'One Way Seats',
                'db_table': 'one_way_seat',
            },
        ),
    ]
