# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0002_auto_20180311_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(max_length=700, verbose_name='Terms And Conditions')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Term and Condition',
                'verbose_name_plural': 'Terms and Conditions',
                'db_table': 'terms_and_conditions',
            },
        ),
    ]
