# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0002_onewayseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdetails',
            name='oneway_date',
            field=models.DateField(blank=True, null=True, verbose_name='One Way Date'),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='oneway_rate_flash',
            field=models.IntegerField(blank=True, null=True, verbose_name='One Way Rate Flash'),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='oneway_rate_supplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='oneway_seat_availability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Departure Seat Availability'),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='oneway_time',
            field=models.TimeField(blank=True, null=True, verbose_name='One Way Time'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='dep_rate_flash',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dep. Rate Flash'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='dep_rate_supplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='departure_seat_availability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Departure Seat Availability'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Departure Time'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='ret_rate_flash',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ret. Rate Flash'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='ret_rate_supplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='return_seat_availability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Return Seat Availability'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='total_departure_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Dep. Seats'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='total_return_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Ret. Seats'),
        ),
    ]
