# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0002_auto_20180222_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdetails',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Return Date'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='return_flt_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ret. Flight No.'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Return Time'),
        ),
    ]
