# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0003_auto_20180301_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdetails',
            name='oneway_flt_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='One Way Flight No.'),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='total_one_way_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total One Way Seats'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='departure_flt_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dep. Flight No.'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='oneway_seat_availability',
            field=models.IntegerField(blank=True, null=True, verbose_name='One Way Seat Availability'),
        ),
    ]
