# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0004_remove_supplierdepartureseatinfo_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='onewayseat',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oneway_seat_sector', to='flight_fixed_departure.Sector'),
        ),
        migrations.AddField(
            model_name='supplierdepartureseatinfo',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_seat_sector', to='flight_fixed_departure.Sector'),
        ),
        migrations.AddField(
            model_name='supplierreturnseatinfo',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_seat_sector', to='flight_fixed_departure.Sector'),
        ),
    ]
