# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0006_auto_20180303_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onewayseat',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
