# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0007_auto_20180306_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onewayseat',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='onewayseat',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='onewayseat',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='onewayseat',
            name='rate_given',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Given Rate'),
        ),
    ]
