# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0007_enquirydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydetails',
            name='supplier',
        ),
        migrations.AddField(
            model_name='enquirydetails',
            name='sector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sector'),
        ),
    ]
