# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0009_auto_20180804_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'GENERATED'), ('IN-PROCESS', 'IN-PROCESS'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='GENERATED', max_length=100),
        ),
    ]
