# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_fixed_departure', '0010_enquirydetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdepartureseatinfo',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='supplierreturnseatinfo',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Number'),
        ),
    ]
