# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('sub_category_images', models.FileField(upload_to='documents/', verbose_name='Images')),
                ('gallery_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.GalleryMenu', verbose_name='Gallery Topic')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Category',
            },
        ),
    ]
