# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerysubcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySubCatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('images', models.FileField(upload_to='documents/', verbose_name='Images')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.GalleryMenu', verbose_name='Sub Category')),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
