# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallerysubcatimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerysubcatimage',
            options={'verbose_name': 'Sub Category Images', 'verbose_name_plural': 'Sub Category Images'},
        ),
        migrations.AlterField(
            model_name='gallerysubcatimage',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.GallerySubCat', verbose_name='Sub Category'),
        ),
    ]
