# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180319_0824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GallerySubCatImage',
            new_name='GalleryImages',
        ),
    ]
