# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_galleryvideos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryvideos',
            options={'verbose_name': 'Sub Category Video', 'verbose_name_plural': 'Sub Category Videos'},
        ),
    ]
