# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassportTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=500, verbose_name='Passport Number')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
            ],
            options={
                'verbose_name': 'Passport Tracking',
                'verbose_name_plural': 'Passport Trackings',
            },
        ),
        migrations.CreateModel(
            name='PassportTrackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_type', models.CharField(max_length=500, verbose_name='Track Type')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Tracking Type',
                'verbose_name_plural': 'Tracking Types',
            },
        ),
        migrations.AddField(
            model_name='passporttrack',
            name='track_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.PassportTrackType', verbose_name='Track Type'),
        ),
    ]
