# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_visaprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaprofile',
            name='mobile_num',
            field=models.CharField(max_length=15, unique=True, verbose_name='Mobile Number'),
        ),
    ]
