# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0004_auto_20180415_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('image', models.FileField(upload_to='documents/', verbose_name='Image')),
                ('details', models.CharField(max_length=500, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
