# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0005_visacountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_details', models.TextField(verbose_name='visa details')),
                ('visa_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.VisaCountry')),
            ],
            options={
                'verbose_name': 'Visa Detail',
                'verbose_name_plural': 'Visa Details',
            },
        ),
    ]
