# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0006_visainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaDownloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('image', models.FileField(upload_to='documents/', verbose_name='Files')),
                ('visa_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.VisaCountry')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
            },
        ),
    ]
