# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0010_passporttrack_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passporttrack',
            name='added_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
