# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0014_auto_20180602_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='passporttrack',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Time'),
        ),
    ]
