# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0015_passporttrack_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passporttrack',
            name='datetime',
        ),
    ]
