# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0017_auto_20180609_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='visahistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
