# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0019_auto_20180804_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='visainfo',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
