# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredSalesAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company Name')),
                ('location', models.CharField(max_length=300, verbose_name='Location')),
                ('person_name', models.CharField(max_length=400, verbose_name='Person Name')),
                ('contact_number', models.CharField(max_length=500, verbose_name='Contact')),
                ('email_id', models.CharField(max_length=500, verbose_name='Email Id')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Perferred Sales Agent',
                'verbose_name_plural': 'Preferred Sales Agents',
            },
        ),
    ]
