# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredsalesagent',
            name='contact_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='preferredsalesagent',
            name='email_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='preferredsalesagent',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='preferredsalesagent',
            name='person_name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Person Name'),
        ),
    ]
