# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('image', models.FileField(upload_to='documents/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.CharField(max_length=500, verbose_name='Link')),
                ('url_text', models.CharField(max_length=500, verbose_name='Link Text')),
            ],
            options={
                'verbose_name': 'Service Detail',
                'verbose_name_plural': 'Service Details',
            },
        ),
    ]
