# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSendEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email_address', models.CharField(max_length=100, verbose_name='Email Id')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Send Enquiry',
                'verbose_name_plural': 'Send Enquiries',
            },
        ),
    ]
