# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicesendenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesendenquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicesendenquiry',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Send Email'),
        ),
        migrations.AddField(
            model_name='servicesendenquiry',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='Send SMS'),
        ),
        migrations.AddField(
            model_name='servicesendenquiry',
            name='sms_or_email_message',
            field=models.TextField(blank=True, null=True, verbose_name='Email or SMS Message'),
        ),
        migrations.AddField(
            model_name='servicesendenquiry',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'GENERATED'), ('IN-PROCESS', 'IN-PROCESS'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='GENERATED', max_length=100),
        ),
    ]
