# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_exchange', '0003_auto_20180603_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('details', models.TextField(verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Terms and Condition',
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
    ]
