# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_exchange', '0004_termsandcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='status',
            field=models.CharField(choices=[('IN-PROGRESS', 'IN-PROGRESS'), ('COMPLETED', 'COMPLETED')], default='IN-PROGRESS', max_length=100),
        ),
    ]
