# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_exchange', '0005_enquirydetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Send SMS'),
        ),
        migrations.AddField(
            model_name='enquirydetails',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='Send SMS'),
        ),
        migrations.AddField(
            model_name='enquirydetails',
            name='sms_or_email_message',
            field=models.TextField(blank=True, null=True, verbose_name='Email or SMS Message'),
        ),
    ]
