# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_exchange', '0007_auto_20180722_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
