# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_exchange', '0008_enquirydetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirydetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
