# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('image', models.FileField(upload_to='documents/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Image Slider',
                'verbose_name_plural': 'Image Sliders',
            },
        ),
    ]
