# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='about',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
