# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_auto_20180825_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='first_image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First image name'),
        ),
        migrations.AddField(
            model_name='about',
            name='first_image_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First image position'),
        ),
        migrations.AddField(
            model_name='about',
            name='second_image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Second image name'),
        ),
        migrations.AddField(
            model_name='about',
            name='second_image_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Second image position'),
        ),
    ]
