# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300, verbose_name='Country')),
                ('product', models.CharField(max_length=300, verbose_name='Product')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company Name')),
                ('email_id', models.CharField(max_length=300, verbose_name='Email Id')),
                ('contact_name', models.CharField(max_length=300, verbose_name='Contact Name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('bank_detail', models.TextField(verbose_name='Bank Details')),
                ('HO_address_and_branches', models.TextField(verbose_name='HO addresss and branches')),
                ('website', models.CharField(max_length=300, verbose_name='Website')),
                ('remark', models.TextField(verbose_name='Remark')),
            ],
            options={
                'verbose_name': 'Supplier Directory',
                'verbose_name_plural': 'Supplier Directories',
            },
        ),
    ]
