# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdir', '0002_auto_20180516_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdirectory',
            name='supplier_images',
            field=models.ManyToManyField(blank=True, null=True, to='supplierdir.SupplierImages', verbose_name='Supplier Images'),
        ),
    ]
