# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdir', '0004_auto_20180516_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierimages',
            old_name='package',
            new_name='supplier',
        ),
    ]
