# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdir', '0006_auto_20180522_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdirectory',
            name='HO_Contact',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='supplierdirectory',
            name='HO_email',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='HO_address_and_branches',
            field=models.TextField(blank=True, null=True, verbose_name='HO addresss'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='bank_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Bank Details'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='contact_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='email_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='product',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Website'),
        ),
    ]
