# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdir', '0007_auto_20180527_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='email_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='HO_Contact',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='HO Contact Number'),
        ),
        migrations.AlterField(
            model_name='supplierdirectory',
            name='HO_email',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='HO Email Id'),
        ),
    ]
