# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passportinfo',
            options={'verbose_name': 'Passport', 'verbose_name_plural': 'Passports'},
        ),
    ]
