# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_auto_20180522_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportinfo',
            name='applicant_aadhaar_num',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Aadhaar Number'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='applicant_citizenship',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Citizenship of India by'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='applicant_district',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='applicant_marital_status',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='applicant_pan_no',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='PAN'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='applicant_state',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='State/UT'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='applicant_voter_id',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Voter Id'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='application',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Applying for'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='application_type',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Type of Application'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='applied_passport_not_issued',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you ever applied for passport, but not issued ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='convicted_court',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you at any time during the period of 5 years immediately preceding the date of this application been convicted by a court in India for any criminal offence and sentenced to imprisonment for two years and more ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='criminal_state',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you ever been charged with criminal proceedings or is any arrest warrant/summon pending before a court in India ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='da_available',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Details of Previous/Current Diplomatic/Official Passport.'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Educational Qualification'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='emergency_certificate',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you ever returned to India on Emergency Certificate (EC) or were ever deported or repatriated ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='emergency_email_id',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='E-Mail Id'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='emergency_mobile_number',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='emergency_name_and_address',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Name and Address'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='emergency_telephone_number',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='emp_type',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='ever_hold_ic',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you ever held/hold any Identity Certificate ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='family_father_name',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="Father's Given Name"),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='family_father_surname',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='family_mother_name',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="Mother's Given Name"),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='family_mother_surname',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='father_or_legal_guardian_nationality',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="Father/Legal Guardian's Nationality, If not Indian"),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='father_or_legal_guardian_passport_number',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="Father/Legal Guardian's File/Passport Number"),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='given_name',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='govern_service',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Is either of your parent (in case of minor)/spouse, a government servant?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='house_no_and_street_name',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='House No. and Street Name'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='is_place_of_birth',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Is your Place of Birth out of India ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='legal_guardian_given_name',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="Legal Guardian's Given Name"),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='legal_guardian_given_surname',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='mother_or_legal_guardian_nationality',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="Mother/Legal Guardian's Nationality, If not Indian"),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='mother_or_legal_guardian_passport_number',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="Mother/Legal Guardian's File/Passport Number"),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='name_change',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you ever changed your name ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='non_ncr',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Is applicant eligible for Non-ECR category ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='other_known_name',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you ever been known by other names ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='pass_booklet',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Type of Passport Booklet'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='passport_deny',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you ever been refused/denied passport ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='passport_impounded',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Has your passport ever been impounded or revoked ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='political_asylum',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Have you ever applied for or been granted political asylum to/by any foreign country ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_address_out_of_india',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Is your present address out of India ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_city',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Village/Town/City'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_district',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_email_id',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='E-Mail Id'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_mob_num',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_permanent_add_available',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Is Permanent Address Available ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_permanent_add_same',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Is your permanent address same as present address ?'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_pin_code',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Pin Code'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_police_station',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Police Station'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_state',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='State/UT'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='present_tele_num',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='residing_since',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Residing Since'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='visible_mark',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Visible distinguishing Mark'),
        ),
    ]
