# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0004_auto_20180729_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportinfo',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="Spouse's Given Name"),
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='spouse_surname',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Surname'),
        ),
    ]
