# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Topic')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
    ]
