# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('tour_images', models.FileField(upload_to='documents/', verbose_name='Tour Images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='tours',
            name='tour_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_packages.Topics', verbose_name='Tour Topic'),
        ),
    ]
