# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-17 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_packages', '0003_auto_20180315_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450, verbose_name='Title')),
                ('package_images', models.FileField(upload_to='documents/', verbose_name='Package Images')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_packages.Packages', verbose_name='Tours')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
