# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-17 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_packages', '0004_packages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'verbose_name': ' Package', 'verbose_name_plural': ' Packages'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': '  Topic', 'verbose_name_plural': '  Topics'},
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': '  Tour', 'verbose_name_plural': '  Tours'},
        ),
        migrations.AlterField(
            model_name='packages',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_packages.Tours', verbose_name='Tours'),
        ),
    ]
