# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-18 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_packages', '0009_auto_20180317_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Title')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('inclusion', models.TextField(blank=True, null=True, verbose_name='Inclusion')),
                ('files', models.ManyToManyField(to='tour_packages.PackageImages')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_packages.TourPackages', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Package Details',
                'verbose_name_plural': 'Package Details',
            },
        ),
    ]
