# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-18 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_packages', '0010_packagedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetails',
            name='files',
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='exclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Exclusion'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='how_to_book',
            field=models.TextField(blank=True, null=True, verbose_name='How to book'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='map_image',
            field=models.FileField(default=None, upload_to='documents/', verbose_name='Map Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='package_images',
            field=models.ManyToManyField(to='tour_packages.PackageImages', verbose_name='Package Images'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='tour_info',
            field=models.TextField(blank=True, null=True, verbose_name='Tour Info'),
        ),
    ]
