# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour_packages', '0011_auto_20180318_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackageEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('mobile_num', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email_id', models.CharField(max_length=100, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('sms_or_email_message', models.TextField(blank=True, null=True, verbose_name='Email or SMS Message')),
                ('send_sms', models.BooleanField(default=False, verbose_name='Send SMS')),
                ('send_email', models.BooleanField(default=False, verbose_name='Send Email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
