# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0002_vehiclemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='Details')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CityTerms', to='cabbooking.Cities')),
            ],
            options={
                'verbose_name': 'Terms and Condition',
                'verbose_name_plural': 'Term and Conditions',
            },
        ),
    ]
