# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0003_termsandcondition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsandcondition',
            options={'verbose_name': 'Terms and Condition', 'verbose_name_plural': 'Terms and Conditions'},
        ),
    ]
