# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0004_auto_20180422_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('four_hour', models.CharField(max_length=10, verbose_name='04 HRS')),
                ('eight_hour', models.CharField(max_length=10, verbose_name='08 HRS')),
                ('twelve_hour', models.CharField(max_length=10, verbose_name='12 HRS')),
                ('extra_per_km', models.CharField(max_length=10, verbose_name='Extra Per KM')),
                ('extra_per_hour', models.CharField(max_length=10, verbose_name='Extra Per Hour')),
                ('outstation_per_km', models.CharField(max_length=10, verbose_name='Outstation Per KM')),
                ('outstation_per_hour', models.CharField(max_length=10, verbose_name='Outstation Per Hour')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CityTariff', to='cabbooking.Cities', verbose_name='City')),
                ('vehicle_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TariffVehicle', to='cabbooking.VehicleMaster', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Tariff Detail',
                'verbose_name_plural': 'Tariff Details',
            },
        ),
    ]
