# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-29 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0006_auto_20180423_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabRegisteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200, verbose_name='Agency Name')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('mobile_no', models.CharField(max_length=200, verbose_name='Mobile No')),
                ('email_id', models.CharField(max_length=200, verbose_name='Email Id')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Bank Name')),
                ('account_no', models.CharField(max_length=200, verbose_name='Account No')),
                ('name_in_account', models.CharField(max_length=200, verbose_name='Account Name')),
                ('ifsc_code', models.CharField(max_length=200, verbose_name='IFSC Code')),
                ('branch', models.CharField(max_length=200, verbose_name='Branch')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Cab Registeration',
                'verbose_name_plural': 'Cab Registerations',
            },
        ),
        migrations.CreateModel(
            name='RegisterVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicle', models.CharField(max_length=200, verbose_name='Vehicle Type')),
                ('purchase_date', models.CharField(max_length=200, verbose_name='Purchase Date')),
                ('cab_no', models.CharField(max_length=200, verbose_name='Cab Number')),
                ('cabregister', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabbooking.CabRegisteration')),
            ],
            options={
                'verbose_name': 'Registered Vehicle',
                'verbose_name_plural': 'Registered Vehicles',
            },
        ),
    ]
