# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-29 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0007_cabregisteration_registervehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200, verbose_name='Agency Name')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('mobile_no', models.CharField(max_length=200, verbose_name='Mobile No')),
                ('email_id', models.CharField(max_length=200, verbose_name='Email Id')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Bank Name')),
                ('account_no', models.CharField(max_length=200, verbose_name='Account No')),
                ('name_in_account', models.CharField(max_length=200, verbose_name='Account Name')),
                ('ifsc_code', models.CharField(max_length=200, verbose_name='IFSC Code')),
                ('branch', models.CharField(max_length=200, verbose_name='Branch')),
                ('address', models.TextField(verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Cab Registeration',
                'verbose_name_plural': 'Cab Registerations',
            },
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='cabregister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabbooking.CabRegister'),
        ),
        migrations.DeleteModel(
            name='CabRegisteration',
        ),
    ]
