# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0008_auto_20180429_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': '   City', 'verbose_name_plural': '   Cities'},
        ),
        migrations.AlterModelOptions(
            name='tariffdetails',
            options={'verbose_name': ' Tariff Detail', 'verbose_name_plural': ' Tariff Details'},
        ),
        migrations.AlterModelOptions(
            name='tariffenquiry',
            options={'verbose_name': ' Tariff Enquiry', 'verbose_name_plural': ' Tariff Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemaster',
            options={'verbose_name': '  Vehicle', 'verbose_name_plural': '  Vehicles'},
        ),
    ]
