# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0009_auto_20180430_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffdetails',
            name='ten_hour',
            field=models.CharField(default='0', max_length=10, verbose_name='10 HRS'),
        ),
    ]
