# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0010_tariffdetails_ten_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffdetails',
            name='eight_hour',
            field=models.CharField(max_length=10, verbose_name='8 Hrs/80 Kms'),
        ),
        migrations.AlterField(
            model_name='tariffdetails',
            name='four_hour',
            field=models.CharField(max_length=10, verbose_name='4 Hrs/40 Kms'),
        ),
        migrations.AlterField(
            model_name='tariffdetails',
            name='outstation_per_hour',
            field=models.CharField(max_length=10, verbose_name='Outstation Per Day'),
        ),
        migrations.AlterField(
            model_name='tariffdetails',
            name='ten_hour',
            field=models.CharField(default='0', max_length=10, verbose_name='10 Hrs/100 Kms'),
        ),
        migrations.AlterField(
            model_name='tariffdetails',
            name='twelve_hour',
            field=models.CharField(max_length=10, verbose_name='12 Hrs/120 Kms'),
        ),
    ]
