# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0011_auto_20180501_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervehicle',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Vehicle Image'),
        ),
    ]
