# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0012_registervehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPickUpDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routename', models.CharField(max_length=200, verbose_name='Route Name')),
                ('fromlocation', models.CharField(max_length=200, verbose_name='From Location')),
                ('tolocation', models.CharField(max_length=200, verbose_name='To Location')),
                ('pickupdate', models.CharField(max_length=200, verbose_name='Pick Up Date')),
                ('pickuptime', models.CharField(max_length=200, verbose_name='Pick Up Time')),
                ('vehiclename', models.CharField(max_length=200, verbose_name='Vehicle Name')),
                ('vehicleimage', models.CharField(max_length=200, verbose_name='Vehicle Image')),
                ('vehiclecategory', models.CharField(max_length=200, verbose_name='Vehicle Category')),
                ('vehicleprice', models.CharField(max_length=200, verbose_name='Vehicle Price')),
            ],
            options={
                'verbose_name': 'Extra Pick Up Drop',
                'verbose_name_plural': 'Extra Pick Up Drop',
            },
        ),
    ]
