# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0013_extrapickupdrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapickupdrop',
            name='vehicleimage',
            field=models.FileField(upload_to='documents/', verbose_name='Vehicle Image'),
        ),
    ]
