# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0015_auto_20180623_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPickUpDropRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_num', models.CharField(max_length=200, verbose_name='Mobile Number')),
                ('email_id', models.CharField(max_length=200, verbose_name='Email Id')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('pick_up_date', models.CharField(max_length=200, verbose_name='Pick Up Date')),
                ('pick_up_time', models.CharField(max_length=200, verbose_name='Pick Up Time')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Extra Pick Up Drop Request',
                'verbose_name_plural': 'Extra Pick Up Drop Requests',
            },
        ),
        migrations.AlterModelOptions(
            name='extrapickupdrop',
            options={'verbose_name': 'Extra Pick Up Drop', 'verbose_name_plural': 'Extra Pick Up Drops'},
        ),
        migrations.AddField(
            model_name='extrapickupdroprequest',
            name='route_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabbooking.ExtraPickUpDrop'),
        ),
    ]
