# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0016_auto_20180624_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapickupdrop',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='extrapickupdroprequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
