# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0017_auto_20180624_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapickupdroprequest',
            name='drop_address_with_landmark',
            field=models.TextField(blank=True, null=True, verbose_name='Drop Address With Landmark'),
        ),
        migrations.AddField(
            model_name='extrapickupdroprequest',
            name='pickup_address_with_landmark',
            field=models.TextField(blank=True, null=True, verbose_name='Pick Up Address With Landmark'),
        ),
    ]
