# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0020_pickupdroplive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpDropLiveTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('details', models.TextField(verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Pick Up Drop Live Term',
                'verbose_name_plural': 'Pick Up Drop Live Terms',
            },
        ),
    ]
