# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0022_timechange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timechange',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='timechange',
            name='minute',
        ),
        migrations.AddField(
            model_name='timechange',
            name='hour_for_airport_pickup_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hour For Airport Pickup Point'),
        ),
        migrations.AddField(
            model_name='timechange',
            name='hour_for_residence_pickup_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hour For Residence Pickup Point'),
        ),
        migrations.AddField(
            model_name='timechange',
            name='minute_for_airport_pickup_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minute For Airport Pickup Point'),
        ),
        migrations.AddField(
            model_name='timechange',
            name='minute_for_residence_pickup_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minute For Residence Pickup Point'),
        ),
        migrations.AddField(
            model_name='timechange',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
