# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0023_auto_20180630_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timechange',
            name='hour_for_residence_pickup_point',
        ),
        migrations.RemoveField(
            model_name='timechange',
            name='minute_for_residence_pickup_point',
        ),
        migrations.AddField(
            model_name='timechange',
            name='hour_for_residence_pickup_point_of_domestic_airport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hour For Residence Pickup Point  Of Domestic Airport'),
        ),
        migrations.AddField(
            model_name='timechange',
            name='hour_for_residence_pickup_point_of_international_airport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hour For Residence Pickup Point  Of International Airport'),
        ),
        migrations.AddField(
            model_name='timechange',
            name='minute_for_residence_pickup_point_of_domestic_airport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minute For Residence Pickup Point Of Domestic Airport'),
        ),
        migrations.AddField(
            model_name='timechange',
            name='minute_for_residence_pickup_point_of_international_airport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minute For Residence Pickup Point Of Domestic International Airport'),
        ),
    ]
