# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0024_auto_20180630_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timechange',
            name='minute_for_residence_pickup_point_of_international_airport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minute For Residence Pickup Point Of International Airport'),
        ),
    ]
