# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0025_auto_20180703_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabregister',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
