# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0026_cabregister_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabregister',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
