# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0027_cabregister_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapickupdrop',
            name='action',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('NOT-AVAILABLE', 'NOT-AVAILABLE'), ('BOOKED', 'BOOKED'), ('DEACTIVATED', 'DEACTIVATED')], default='AVAILABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='extrapickupdrop',
            name='routename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Route Name'),
        ),
    ]
