# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0029_auto_20180804_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickDropLiveTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pick Up Drop Live Trip',
                'verbose_name_plural': 'Pick Up Drop Live Trips',
            },
        ),
    ]
