# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0030_pickdroplivetrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabregister',
            options={'verbose_name': 'Cab Registration', 'verbose_name_plural': 'Cab Registrations'},
        ),
        migrations.AddField(
            model_name='extrapickupdroprequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='extrapickupdroprequest',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Send Email'),
        ),
        migrations.AddField(
            model_name='extrapickupdroprequest',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='Send SMS'),
        ),
        migrations.AddField(
            model_name='extrapickupdroprequest',
            name='sms_or_email_message',
            field=models.TextField(blank=True, null=True, verbose_name='Email or SMS Message'),
        ),
    ]
