# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabbooking', '0032_auto_20180821_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLiveTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('details', models.TextField(verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Shared Cab Term',
                'verbose_name_plural': 'Shared Cab Terms',
            },
        ),
        migrations.AlterModelOptions(
            name='pickupdropliveterms',
            options={'verbose_name': 'Individual Cab Term', 'verbose_name_plural': 'Individual Cab Terms'},
        ),
    ]
