# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Title')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('inclusion', models.TextField(blank=True, null=True, verbose_name='Inclusion')),
                ('exclusion', models.TextField(blank=True, null=True, verbose_name='Exclusion')),
                ('how_to_book', models.TextField(blank=True, null=True, verbose_name='How to book')),
                ('hotel_info', models.TextField(blank=True, null=True, verbose_name='Hotel Info')),
                ('map_image', models.FileField(upload_to='documents/', verbose_name='Map Image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_deals.Hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Details',
                'verbose_name_plural': 'Hotel Details',
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450, verbose_name='Title')),
                ('hotel_images', models.FileField(upload_to='documents/', verbose_name='Hotel Image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_deals.Hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Image',
                'verbose_name_plural': 'Hotel Images',
            },
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='hotel_images',
            field=models.ManyToManyField(to='hotel_deals.HotelImages', verbose_name='Hotel Images'),
        ),
    ]
