# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_deals', '0002_auto_20180408_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '  City', 'verbose_name_plural': '  Cities'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': ' Hotel', 'verbose_name_plural': ' Hotels'},
        ),
    ]
