# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_deals', '0003_auto_20180410_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('email_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Id')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject')),
                ('sms_or_email_message', models.TextField(blank=True, null=True, verbose_name='Email or SMS Message')),
                ('send_sms', models.BooleanField(default=False, verbose_name='Send SMS')),
                ('send_email', models.BooleanField(default=False, verbose_name='Send Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Enquiry Detail',
                'verbose_name_plural': 'Enquiry Details',
            },
        ),
    ]
